# Generated by Django 4.1.1 on 2022-09-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('P', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('K', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mg', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('S', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Ca', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Fe', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mn', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Zn', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Cu', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('B', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mo', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Co', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Ni', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Se', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Посчитанные значения',
                'verbose_name_plural': 'Посчитанные значения',
            },
        ),
        migrations.CreateModel(
            name='ClimateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_zone', models.CharField(default='', max_length=50, verbose_name='Климатическая зона')),
            ],
            options={
                'verbose_name': 'Климатическая зона',
                'verbose_name_plural': 'Климатические зоны',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(max_length=20, verbose_name='Культура')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культуры',
            },
        ),
        migrations.CreateModel(
            name='DefaultElementsConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('P', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('K', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mg', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('S', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Ca', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Fe', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mn', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Zn', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Cu', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('B', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mo', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Co', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Ni', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Se', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Содержание элементов по умолчанию',
                'verbose_name_plural': 'Содержание элементов по умолчанию',
            },
        ),
        migrations.CreateModel(
            name='UserFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_water', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('productivity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('N', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('P', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('K', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Mg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('S', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Ca', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Fe', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Mn', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Zn', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Cu', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('B', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Mo', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Co', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Ni', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Se', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('climate_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calcfertapi.climatezone')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calcfertapi.culture')),
            ],
            options={
                'verbose_name': 'Данные из формы',
                'verbose_name_plural': 'Данные из формы',
            },
        ),
        migrations.CreateModel(
            name='ElementsConsuption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('P', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('K', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mg', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('S', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Ca', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Fe', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mn', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Zn', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Cu', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('B', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Mo', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Co', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Ni', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('Se', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calcfertapi.culture')),
            ],
            options={
                'verbose_name': 'Вынос элементов',
                'verbose_name_plural': 'Вынос элементов',
            },
        ),
    ]
