# Generated by Django 4.1.1 on 2022-09-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcfertapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementsConsuption',
            new_name='ElementsConsumption',
        ),
    ]
