# Generated by Django 4.1.1 on 2022-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcfertapi', '0002_rename_elementsconsuption_elementsconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformdata',
            name='climate_zone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userformdata',
            name='culture',
            field=models.CharField(default='', max_length=20),
        ),
    ]
