version: '3'

services:
  backend:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  
  nginx:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

