version: "3"

services:
  backend:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  nginx:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - certbot
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email your.email@example.com --agree-tos -d example.com
